server:
  port: 8090
  servlet:
    context-path: /terminals
spring:
  datasource:
    url: jdbc:mysql://cdb-17ejfrt8.cd.tencentcdb.com:10004/terminals?useUnicode=true&amp&characterEncoding=utf8&useSSL=false
    username: root
    password: Mysql@3306
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 106.14.119.243
    port: 6379
    password:
    timeout: 30000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    #配置rabbitmq的安装地址、端口以及账户信息
    #注意port 15672是管理端的端口
  rabbitmq:
    host: 106.14.119.243
    port: 5672
    username: user
    password: password

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

elastic:
  job:
    zk:
      serverLists: 123.207.198.100:2181
      namespace: spring-boot-ejob