package com.beard.terminals.pipeline.mapper;

import com.beard.terminals.pipeline.domain.PipelineTask;
import com.beard.terminals.pipeline.domain.PipelineTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PipelineTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    int countByExample(PipelineTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    int deleteByExample(PipelineTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    int insert(PipelineTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    int insertSelective(PipelineTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    List<PipelineTask> selectByExampleWithBLOBs(PipelineTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    List<PipelineTask> selectByExample(PipelineTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    PipelineTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PipelineTask record, @Param("example") PipelineTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") PipelineTask record, @Param("example") PipelineTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PipelineTask record, @Param("example") PipelineTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PipelineTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(PipelineTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PipelineTask record);
}