package com.beard.terminals.pipeline.domain;

import java.io.Serializable;
import java.util.Date;

public class PipelineTask implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_task.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_task.serial
     *
     * @mbggenerated
     */
    private String serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_task.exec_status
     *
     * @mbggenerated
     */
    private String execStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_task.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_task.trans_result
     *
     * @mbggenerated
     */
    private String transResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_task.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_task.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_task.request_param
     *
     * @mbggenerated
     */
    private String requestParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_task.id
     *
     * @return the value of pipeline_task.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_task.id
     *
     * @param id the value for pipeline_task.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_task.serial
     *
     * @return the value of pipeline_task.serial
     *
     * @mbggenerated
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_task.serial
     *
     * @param serial the value for pipeline_task.serial
     *
     * @mbggenerated
     */
    public void setSerial(String serial) {
        this.serial = serial == null ? null : serial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_task.exec_status
     *
     * @return the value of pipeline_task.exec_status
     *
     * @mbggenerated
     */
    public String getExecStatus() {
        return execStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_task.exec_status
     *
     * @param execStatus the value for pipeline_task.exec_status
     *
     * @mbggenerated
     */
    public void setExecStatus(String execStatus) {
        this.execStatus = execStatus == null ? null : execStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_task.name
     *
     * @return the value of pipeline_task.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_task.name
     *
     * @param name the value for pipeline_task.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_task.trans_result
     *
     * @return the value of pipeline_task.trans_result
     *
     * @mbggenerated
     */
    public String getTransResult() {
        return transResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_task.trans_result
     *
     * @param transResult the value for pipeline_task.trans_result
     *
     * @mbggenerated
     */
    public void setTransResult(String transResult) {
        this.transResult = transResult == null ? null : transResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_task.created_at
     *
     * @return the value of pipeline_task.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_task.created_at
     *
     * @param createdAt the value for pipeline_task.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_task.updated_at
     *
     * @return the value of pipeline_task.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_task.updated_at
     *
     * @param updatedAt the value for pipeline_task.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_task.request_param
     *
     * @return the value of pipeline_task.request_param
     *
     * @mbggenerated
     */
    public String getRequestParam() {
        return requestParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_task.request_param
     *
     * @param requestParam the value for pipeline_task.request_param
     *
     * @mbggenerated
     */
    public void setRequestParam(String requestParam) {
        this.requestParam = requestParam == null ? null : requestParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_task
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", serial=").append(serial);
        sb.append(", execStatus=").append(execStatus);
        sb.append(", name=").append(name);
        sb.append(", transResult=").append(transResult);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", requestParam=").append(requestParam);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}