package com.beard.terminals.pipeline.domain;

import java.io.Serializable;
import java.util.Date;

public class PipelineProcess implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_process.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_process.task_serial
     *
     * @mbggenerated
     */
    private String taskSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_process.exec_status
     *
     * @mbggenerated
     */
    private String execStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_process.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_process.order
     *
     * @mbggenerated
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_process.class_name
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_process.try_no
     *
     * @mbggenerated
     */
    private Integer tryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_process.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_process.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pipeline_process.param
     *
     * @mbggenerated
     */
    private String param;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pipeline_process
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_process.id
     *
     * @return the value of pipeline_process.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_process.id
     *
     * @param id the value for pipeline_process.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_process.task_serial
     *
     * @return the value of pipeline_process.task_serial
     *
     * @mbggenerated
     */
    public String getTaskSerial() {
        return taskSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_process.task_serial
     *
     * @param taskSerial the value for pipeline_process.task_serial
     *
     * @mbggenerated
     */
    public void setTaskSerial(String taskSerial) {
        this.taskSerial = taskSerial == null ? null : taskSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_process.exec_status
     *
     * @return the value of pipeline_process.exec_status
     *
     * @mbggenerated
     */
    public String getExecStatus() {
        return execStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_process.exec_status
     *
     * @param execStatus the value for pipeline_process.exec_status
     *
     * @mbggenerated
     */
    public void setExecStatus(String execStatus) {
        this.execStatus = execStatus == null ? null : execStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_process.name
     *
     * @return the value of pipeline_process.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_process.name
     *
     * @param name the value for pipeline_process.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_process.order
     *
     * @return the value of pipeline_process.order
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_process.order
     *
     * @param order the value for pipeline_process.order
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_process.class_name
     *
     * @return the value of pipeline_process.class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_process.class_name
     *
     * @param className the value for pipeline_process.class_name
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_process.try_no
     *
     * @return the value of pipeline_process.try_no
     *
     * @mbggenerated
     */
    public Integer getTryNo() {
        return tryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_process.try_no
     *
     * @param tryNo the value for pipeline_process.try_no
     *
     * @mbggenerated
     */
    public void setTryNo(Integer tryNo) {
        this.tryNo = tryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_process.created_at
     *
     * @return the value of pipeline_process.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_process.created_at
     *
     * @param createdAt the value for pipeline_process.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_process.updated_at
     *
     * @return the value of pipeline_process.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_process.updated_at
     *
     * @param updatedAt the value for pipeline_process.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pipeline_process.param
     *
     * @return the value of pipeline_process.param
     *
     * @mbggenerated
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pipeline_process.param
     *
     * @param param the value for pipeline_process.param
     *
     * @mbggenerated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipeline_process
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", taskSerial=").append(taskSerial);
        sb.append(", execStatus=").append(execStatus);
        sb.append(", name=").append(name);
        sb.append(", order=").append(order);
        sb.append(", className=").append(className);
        sb.append(", tryNo=").append(tryNo);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", param=").append(param);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}